name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git 
        run: sudo apt-get install git

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Rust project
        run: cargo run

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
